/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BanksController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminCategoriesController_list"];
        put?: never;
        post: operations["AdminCategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminCategoriesController_update"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_publicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListingsController_search"];
        put?: never;
        post: operations["ListingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListingsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ListingsController_update"];
        trace?: never;
    };
    "/listings/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListingsController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListingsController_reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListingsController_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MyListingsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{listingId}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListingImagesController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{listingId}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ListingImagesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrdersController_listMine"];
        put?: never;
        post: operations["OrdersController_place"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrdersController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["OrdersController_edit"];
        trace?: never;
    };
    "/orders/{id}/report-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_reportPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/confirm-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/reject-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_rejectPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_deliver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SalesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{listingId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SummaryController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{listingId}/summary.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SummaryController_csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{listingId}/orders/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SummaryController_bulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BankResponseDto: {
            /** @example 970436 */
            bin: string;
            /** @example VCB */
            code: string;
            /** @example Vietcombank */
            shortName: string;
            name: string;
        };
        CategoryResponseDto: {
            id: number;
            /** @example thuc-pham-tuoi */
            slug: string;
            /** @example Thực phẩm tươi */
            name: string;
            /** @example Fresh food */
            nameEn: string;
        };
        AdminCategoryDto: {
            id: number;
            /** @example thuc-pham-tuoi */
            slug: string;
            /** @example Thực phẩm tươi */
            name: string;
            /** @example Fresh food */
            nameEn: string;
            sortOrder: number;
            /** @description False when hidden from browsing and selling */
            isActive: boolean;
        };
        CreateCategoryDto: {
            /** @example Sách */
            name: string;
            /** @example Books */
            nameEn: string;
            /** @description Defaults to the end of the list */
            sortOrder?: number;
        };
        UpdateCategoryDto: {
            name?: string;
            nameEn?: string;
            sortOrder?: number;
            isActive?: boolean;
        };
        /** @enum {string} */
        UserRole: "user" | "admin";
        /** @enum {string} */
        UserLocale: "vi" | "en";
        UserResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            avatarUrl: string | null;
            role: components["schemas"]["UserRole"];
            locale: components["schemas"]["UserLocale"];
            deliveryLocation: string | null;
            bankBin: string | null;
            bankAccountNumber: string | null;
            bankAccountName: string | null;
        };
        UpdateProfileDto: {
            deliveryLocation?: string | null;
            /** @example 970436 */
            bankBin?: string | null;
            bankAccountNumber?: string | null;
            bankAccountName?: string | null;
            locale?: components["schemas"]["UserLocale"];
        };
        PublicUserDto: {
            /** Format: uuid */
            id: string;
            name: string;
            avatarUrl: string | null;
            deliveryLocation: string | null;
        };
        /** @enum {string} */
        ListingMode: "in_stock" | "preorder";
        ListingItemInputDto: {
            /**
             * Format: uuid
             * @description When editing: the id of an existing item to keep. Omit for a new item.
             */
            id?: string;
            /** @example Cam sành */
            name: string;
            /**
             * @example kg
             * @enum {string}
             */
            unit: "cái" | "kg" | "hộp" | "túi" | "chai" | "bó" | "combo";
            /**
             * @description Integer VND
             * @example 35000
             */
            unitPrice: number;
            /**
             * @description Decimal string, up to 3 fraction digits. Required for in-stock listings, null for pre-order.
             * @example 2.5
             */
            stockQuantity?: string | null;
        };
        ListingInputDto: {
            mode: components["schemas"]["ListingMode"];
            /** @example Hoa quả tuần 41 */
            title: string;
            /** @example 2 */
            categoryId: number;
            /** @default  */
            description: string;
            acceptsPrepaidQr: boolean;
            acceptsPayOnDelivery: boolean;
            /**
             * Format: date-time
             * @description Pre-order only
             */
            orderDeadline?: string | null;
            /**
             * Format: date
             * @description Pre-order only, YYYY-MM-DD
             */
            deliveryDate?: string | null;
            items: components["schemas"]["ListingItemInputDto"][];
        };
        /** @enum {string} */
        ListingStatus: "draft" | "open" | "closed";
        ListingSellerDto: {
            /** Format: uuid */
            id: string;
            name: string;
            avatarUrl: string | null;
        };
        ListingItemDto: {
            /** Format: uuid */
            id: string;
            name: string;
            unit: string;
            /** @description Integer VND */
            unitPrice: number;
            /** @description Remaining stock; null means unlimited */
            stockQuantity: number | null;
        };
        ListingImageDto: {
            /** Format: uuid */
            id: string;
            url: string;
            thumbnailUrl: string;
        };
        ListingDetailDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            mode: components["schemas"]["ListingMode"];
            status: components["schemas"]["ListingStatus"];
            /** @description True while buyers can see the listing */
            isOpen: boolean;
            category: components["schemas"]["CategoryResponseDto"];
            seller: components["schemas"]["ListingSellerDto"];
            acceptsPrepaidQr: boolean;
            acceptsPayOnDelivery: boolean;
            /** Format: date-time */
            orderDeadline: string | null;
            /** Format: date */
            deliveryDate: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            /** @description Orders that have not been cancelled */
            orderCount: number;
            /**
             * Format: uuid
             * @description The earlier round this listing was reopened from
             */
            reopenedFromId: string | null;
            items: components["schemas"]["ListingItemDto"][];
            images: components["schemas"]["ListingImageDto"][];
        };
        /** @enum {string} */
        ListingSort: "recent" | "deadline";
        ListingSummaryDto: {
            /** Format: uuid */
            id: string;
            title: string;
            mode: components["schemas"]["ListingMode"];
            category: components["schemas"]["CategoryResponseDto"];
            seller: components["schemas"]["ListingSellerDto"];
            thumbnailUrl: string | null;
            /** @description Lowest unit price among the items, integer VND */
            minUnitPrice: number;
            /**
             * @description Unit of the cheapest item
             * @example kg
             */
            minPriceUnit: string;
            /** @description Orders that have not been cancelled */
            orderCount: number;
            /** @description Remaining stock, only for an in-stock listing with exactly one item that has a stock limit; null otherwise */
            stockQuantity: number | null;
            /** Format: date-time */
            orderDeadline: string | null;
            /** Format: date */
            deliveryDate: string | null;
            /** Format: date-time */
            publishedAt: string;
        };
        ListingPageDto: {
            items: components["schemas"]["ListingSummaryDto"][];
            /** @description Pass as `cursor` to get the next page; null on the last page */
            nextCursor: string | null;
        };
        OrderLineInputDto: {
            /** Format: uuid */
            itemId: string;
            /**
             * @description Decimal string, so no precision is lost in transit
             * @example 1.5
             */
            quantity: string;
        };
        /** @enum {string} */
        PaymentMethod: "prepaid_qr" | "pay_on_delivery";
        PlaceOrderDto: {
            /** Format: uuid */
            listingId: string;
            lines: components["schemas"]["OrderLineInputDto"][];
            paymentMethod: components["schemas"]["PaymentMethod"];
            /** @example Tầng 7 */
            deliveryLocation: string;
            note?: string | null;
        };
        OrderListingDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            orderDeadline: string | null;
            /** Format: date */
            deliveryDate: string | null;
        };
        OrderPersonDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @enum {string} */
        OrderActor: "buyer" | "seller";
        /** @enum {string} */
        PaymentStatus: "unpaid" | "reported" | "paid";
        /** @enum {string} */
        FulfillmentStatus: "pending" | "delivered" | "cancelled";
        OrderLineDto: {
            /** Format: uuid */
            itemId: string;
            itemName: string;
            unit: string;
            /** @description Integer VND, as it was when the order was placed */
            unitPrice: number;
            quantity: number;
            /** @description Integer VND */
            lineTotal: number;
        };
        OrderQrDto: {
            /** @description The text to render as a QR code */
            payload: string;
            bankName: string;
            accountNumber: string;
            accountName: string;
            /** @description Integer VND */
            amount: number;
            /** @description Transfer content: the order code */
            content: string;
        };
        OrderDetailDto: {
            /** Format: uuid */
            id: string;
            /** @example SSM7K2Q9X */
            code: string;
            listing: components["schemas"]["OrderListingDto"];
            buyer: components["schemas"]["OrderPersonDto"];
            seller: components["schemas"]["OrderPersonDto"];
            viewerRole: components["schemas"]["OrderActor"];
            isPreorder: boolean;
            paymentMethod: components["schemas"]["PaymentMethod"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            fulfillmentStatus: components["schemas"]["FulfillmentStatus"];
            /** @description Integer VND */
            totalAmount: number;
            deliveryLocation: string;
            note: string | null;
            lines: components["schemas"]["OrderLineDto"][];
            refundNeeded: boolean;
            cancelledBy: components["schemas"]["OrderActor"] | null;
            cancelReason: string | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Present while a QR order is waiting for payment */
            qr: components["schemas"]["OrderQrDto"] | null;
        };
        OrderPageDto: {
            items: components["schemas"]["OrderDetailDto"][];
            nextCursor: string | null;
        };
        EditOrderDto: {
            lines: components["schemas"]["OrderLineInputDto"][];
            paymentMethod: components["schemas"]["PaymentMethod"];
            /** @example Tầng 7 */
            deliveryLocation: string;
            note?: string | null;
        };
        CancelOrderDto: {
            /** @description Required when the seller cancels */
            reason?: string | null;
        };
        SummaryListingDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            orderDeadline: string | null;
            /** Format: date */
            deliveryDate: string | null;
        };
        SummaryItemDto: {
            /** Format: uuid */
            id: string;
            name: string;
            unit: string;
            /** @description False for an item the seller has removed */
            isActive: boolean;
        };
        SummaryBuyerDto: {
            name: string;
            email: string;
        };
        SummaryRowDto: {
            /** Format: uuid */
            orderId: string;
            code: string;
            buyer: components["schemas"]["SummaryBuyerDto"];
            deliveryLocation: string;
            /** @description Quantity per item id; items not ordered are absent */
            quantities: {
                [key: string]: number;
            };
            /** @description Integer VND */
            totalAmount: number;
            paymentMethod: components["schemas"]["PaymentMethod"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            fulfillmentStatus: components["schemas"]["FulfillmentStatus"];
            note: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        SummaryTotalsDto: {
            orderCount: number;
            /** @description Quantity per item id; items not ordered are absent */
            quantities: {
                [key: string]: number;
            };
            /** @description Integer VND */
            totalAmount: number;
            /** @description Sum of orders whose payment is confirmed */
            paidAmount: number;
            /** @description totalAmount minus paidAmount */
            outstandingAmount: number;
        };
        SalesSummaryDto: {
            listing: components["schemas"]["SummaryListingDto"];
            items: components["schemas"]["SummaryItemDto"][];
            rows: components["schemas"]["SummaryRowDto"][];
            /** @description Cancelled orders never count towards totals */
            totals: components["schemas"]["SummaryTotalsDto"];
        };
        BulkOrdersDto: {
            /** @enum {string} */
            action: "deliver" | "confirm_payment";
            orderIds: string[];
        };
        BulkResultDto: {
            /** Format: uuid */
            orderId: string;
            ok: boolean;
            /** @description Why this order was skipped, e.g. INVALID_ORDER_STATE */
            code: string | null;
        };
        BulkResponseDto: {
            results: components["schemas"]["BulkResultDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BanksController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankResponseDto"][];
                };
            };
        };
    };
    CategoriesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseDto"][];
                };
            };
        };
    };
    AdminCategoriesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategoryDto"][];
                };
            };
            /** @description The caller is not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategoryDto"];
                };
            };
            /** @description The caller is not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CATEGORY_EXISTS */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategoryDto"];
                };
            };
            /** @description The caller is not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_publicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserDto"];
                };
            };
            /** @description No such person */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New token cookies were set */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListingsController_search: {
        parameters: {
            query?: {
                /** @description Keywords, with or without diacritics */
                q?: string;
                /** @description Category slug */
                category?: string;
                mode?: components["schemas"]["ListingMode"];
                /** @description `deadline` returns only pre-orders, closing soonest first; it cannot be combined with `q` or `mode=in_stock` */
                sort?: components["schemas"]["ListingSort"];
                /** @description Only this seller */
                seller?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPageDto"];
                };
            };
        };
    };
    ListingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingInputDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
        };
    };
    ListingsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
        };
    };
    ListingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingInputDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
        };
    };
    ListingsController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
        };
    };
    ListingsController_reopen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new draft copied from this finished pre-order round */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
        };
    };
    ListingsController_close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
        };
    };
    MyListingsController_list: {
        parameters: {
            query?: {
                status?: "draft" | "open" | "closed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"][];
                };
            };
        };
    };
    ListingImagesController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingImageDto"];
                };
            };
        };
    };
    ListingImagesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: string;
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_listMine: {
        parameters: {
            query?: {
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPageDto"];
                };
            };
        };
    };
    OrdersController_place: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID generated once per order form */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceOrderDto"];
            };
        };
        responses: {
            /** @description The order this key already created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
        };
    };
    OrdersController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
        };
    };
    OrdersController_edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
        };
    };
    OrdersController_reportPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
        };
    };
    OrdersController_confirmPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
        };
    };
    OrdersController_rejectPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
        };
    };
    OrdersController_deliver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
        };
    };
    OrdersController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailDto"];
                };
            };
        };
    };
    SalesController_list: {
        parameters: {
            query?: {
                listingId?: string;
                paymentStatus?: "unpaid" | "reported" | "paid";
                fulfillmentStatus?: "pending" | "delivered" | "cancelled";
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPageDto"];
                };
            };
        };
    };
    SummaryController_get: {
        parameters: {
            query?: {
                includeCancelled?: boolean;
            };
            header?: never;
            path: {
                listingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesSummaryDto"];
                };
            };
        };
    };
    SummaryController_csv: {
        parameters: {
            query?: {
                includeCancelled?: boolean;
            };
            header?: never;
            path: {
                listingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The summary as a CSV file for Excel, in the caller's language */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SummaryController_bulk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkOrdersDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResponseDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
